최재학님 파일 -> 3월매출 merge해서 매출이랑 매출중량 더하기

In [155]:
import numpy as np

In [97]:
import pandas as pd

jaehak_df = pd.read_excel("단가인상_현황_취합_og_최재학.xlsx", header =5).dropna(subset= '거채처')
jaehak_df = jaehak_df.drop(columns = 'Unnamed: 0')
jaehak_df = jaehak_df[['거채처', '담당자', '1~2월 매출', '1~2월 매출중량\n(TON)','요청\n\/g','예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황']]
jaehak_df = jaehak_df.rename(columns = {'거채처':'거래처'})
jaehak_df

<>:5: SyntaxWarning: invalid escape sequence '\/'
<>:5: SyntaxWarning: invalid escape sequence '\/'
<>:5: SyntaxWarning: invalid escape sequence '\/'
<>:5: SyntaxWarning: invalid escape sequence '\/'
<>:5: SyntaxWarning: invalid escape sequence '\/'
<>:5: SyntaxWarning: invalid escape sequence '\/'
C:\Users\user\AppData\Local\Temp\ipykernel_19392\2701695262.py:5: SyntaxWarning: invalid escape sequence '\/'
  jaehak_df = jaehak_df[['거채처', '담당자', '1~2월 매출', '1~2월 매출중량\n(TON)','요청\n\/g','예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황']]
C:\Users\user\AppData\Local\Temp\ipykernel_19392\2701695262.py:5: SyntaxWarning: invalid escape sequence '\/'
  jaehak_df = jaehak_df[['거채처', '담당자', '1~2월 매출', '1~2월 매출중량\n(TON)','요청\n\/g','예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황']]
C:\Users\user\AppData\Local\Temp\ipykernel_19392\2701695262.py:5: SyntaxWarning: invalid escape sequence '\/'
  jaehak_df = jaehak_df[['거채처', '담당자', '1~2월 매출', '1~2월 매출중량\n(TON)','요청\n\/g','예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황']]

,거래처,담당자,1~2월 매출,1~2월 매출중량\n(TON),요청\n\/g,예상\n\/g,합의\n\/g,적용\n시점,진행상황
0,코웨이,최재학,132665850,18.872,8.295131,8.295131,NaN,NaT,NaN
1,중부스티로폼,이정우,83679876,15.990,6.170000,6.170000,NaN,NaT,운임 별도로 받고 있음
2,한국이노팩,최재학,65196120,12.569,6.100000,5.700000,5.7,2026-04-15,공문발송
3,CJ대한통운,이정우,66095925,11.384,6.560000,6.560000,NaN,NaT,계약 진행중(04/15 반영 예정)
4,동진쎄미켐,이정우,65417640,11.322,6.700000,6.700000,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...
129,센트럴작은동물원,이다영,287600,0.037,8.500000,8.500000,NaN,NaT,NaN
130,육대장,최재학,242352,0.030,9.532512,9.532512,NaN,NaT,NaN
131,배고파,이다영,197680,0.028,8.000000,8.000000,NaN,NaT,NaN
132,도누다,이다영,129600,0.019,8.000000,8.000000,NaN,NaT,NaN
133,찬푸드,이다영,19200,0.003,8.000000,8.000000,NaN,NaT,NaN

In [99]:
import msoffcrypto
import io

file_path = '00_영업실적_2024년~.xlsx'
password = '3101'

# 1. 암호화된 파일 열기
temp_file = io.BytesIO()
with open(file_path, 'rb') as f:
    office_file = msoffcrypto.OfficeFile(f)
    # 비밀번호 입력하여 해독
    office_file.load_key(password=password)
    office_file.decrypt(temp_file)
temp_file.seek(0)
마감자료 = pd.read_excel(temp_file, engine='openpyxl')
마감자료 = 마감자료.dropna(subset= '년도')
마감자료 = 마감자료[['년도', '월', '대분류','합계(운임비/금형비+공급가액)', '중량(Ton)']]
filtered_data = 마감자료[(마감자료['년도'] == 26) & (마감자료['월'] == 3)]
filtered_data = filtered_data.sort_values('중량(Ton)', ascending= False).reset_index(drop = True)
filtered_data

       년도    월          대분류  합계(운임비/금형비+공급가액)  중량(Ton)
0    26.0  3.0      탭스인터내셔널        69965760.0    8.928
1    26.0  3.0        청호나이스        31321814.0    5.190
2    26.0  3.0        한국이노팩        22767666.0    4.411
3    26.0  3.0         SK매직        22946650.0    4.180
4    26.0  3.0        캐논코리아        25118666.0    4.126
..    ...  ...          ...               ...      ...
126  26.0  3.0     센트럴작은동물원           30000.0    0.004
127  26.0  3.0  CJ대한통운/아이스팩        25417152.0    0.000
128  26.0  3.0  CJ대한통운/아이스팩         5588352.0    0.000
129  26.0  3.0     케이듀/아이스팩           84000.0    0.000
130  26.0  3.0   루이스벨라/아이스팩          382240.0    0.000

[131 rows x 5 columns]

In [114]:
#코웨이 가화텍 필터

filtered_data['대분류'] = filtered_data['대분류'].str.replace('^코웨이.*', '코웨이', regex=True)
filtered_data['대분류'] = filtered_data['대분류'].str.replace('^가화텍.*', '가화텍', regex=True)
result = filtered_data.groupby('대분류', as_index=False).sum(numeric_only=True)
result = result.sort_values("중량(Ton)", ascending= False).reset_index(drop= True).drop(columns = ['년도', '월']).rename(columns ={'대분류': '거래처'})
result

             거래처  합계(운임비/금형비+공급가액)  중량(Ton)
0        탭스인터내셔널        69965760.0    8.928
1            코웨이        51977760.0    7.188
2          청호나이스        31321814.0    5.190
3          한국이노팩        22767666.0    4.411
4          동진쎄미켐        24295650.0    4.200
..           ...               ...      ...
104          도누다          143040.0    0.020
105     센트럴작은동물원           30000.0    0.004
106  CJ대한통운/아이스팩        31005504.0    0.000
107   루이스벨라/아이스팩          382240.0    0.000
108     케이듀/아이스팩           84000.0    0.000

[109 rows x 3 columns]

In [122]:
#현재 단가인상자료와 merge
merged = pd.merge(jaehak_df, result, on = '거래처', how = 'outer', indicator= True).fillna(0)   
merged['1~3월매출'] = merged['1~2월 매출'] + merged['합계(운임비/금형비+공급가액)']
merged['1~3월매출중량(TON)'] = merged['1~2월 매출중량\n(TON)'] +  merged['중량(Ton)']
merged

,거래처,담당자,1~2월 매출,1~2월 매출중량\n(TON),요청\n\/g,예상\n\/g,합의\n\/g,적용\n시점,진행상황,합계(운임비/금형비+공급가액),중량(Ton),_merge,1~3월매출,1~3월매출중량(TON)
0,CJ대한통운,이정우,66095925.0,11.384,6.560000,6.560000,0.0,0,계약 진행중(04/15 반영 예정),20152549.0,3.436,both,86248474.0,14.820
1,CJ대한통운/아이스팩,0,0.0,0.000,0.000000,0.000000,0.0,0,0,31005504.0,0.000,right_only,31005504.0,0.000
2,H컴퍼니,최재학,1341550.0,0.248,7.000000,7.000000,7.0,2026-04-15 00:00:00,0,1421480.0,0.248,both,2763030.0,0.496
3,KEC,이정우,2800000.0,0.316,9.700000,9.700000,0.0,0,0,0.0,0.000,left_only,2800000.0,0.316
4,LG서브원,최재학,41443534.0,6.892,7.035539,7.035539,0.0,0,공문발송,18763618.0,3.085,both,60207152.0,9.977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,현대포장,0,0.0,0.000,0.000000,0.000000,0.0,0,0,939200.0,0.114,right_only,939200.0,0.114
153,현진금속,최재학,2022570.0,0.175,13.637901,13.637901,0.0,0,오비오와 협의 중,6389000.0,0.405,both,8411570.0,0.580
154,현진로지스,이다영,975040.0,0.112,10.000000,10.000000,10.0,0,운반비 별도 16만원청구,1279360.0,0.112,both,2254400.0,0.224
155,혜천푸드,이다영,255240.0,0.039,8.000000,8.000000,0.0,0,0,0.0,0.000,left_only,255240.0,0.039
156,히즈테이블,0,0.0,0.000,0.000000,0.000000,0.0,0,0,689200.0,0.085,right_only,689200.0,0.085

In [123]:
merged = merged.sort_values("1~3월매출중량(TON)", ascending= False).reset_index(drop= True)

In [199]:
merged_final = merged[['거래처', '1~3월매출', '1~3월매출중량(TON)', '요청\n\/g', '예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황','_merge']]

<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
C:\Users\user\AppData\Local\Temp\ipykernel_19392\2299246556.py:1: SyntaxWarning: invalid escape sequence '\/'
  merged_final = merged[['거래처', '1~3월매출', '1~3월매출중량(TON)', '요청\n\/g', '예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황','_merge']]
C:\Users\user\AppData\Local\Temp\ipykernel_19392\2299246556.py:1: SyntaxWarning: invalid escape sequence '\/'
  merged_final = merged[['거래처', '1~3월매출', '1~3월매출중량(TON)', '요청\n\/g', '예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황','_merge']]
C:\Users\user\AppData\Local\Temp\ipykernel_19392\2299246556.py:1: SyntaxWarning: invalid escape sequence '\/'
  merged_final = merged[['거래처', '1~3월매출', '1~3월매출중량(TON)', '요청\n\/g', '예상\n\/g', '합의\n\/g', '적용\n시점', '진행상황','_merge']]

In [200]:
# 적용시점 데이트 바꾸는중..
merged_final['적용\n시점'] = merged_final['적용\n시점'].replace(0,'null')
# 1. Convert to datetime (if it isn't already)
merged_final['적용\n시점'] = pd.to_datetime(merged_final['적용\n시점'], errors='coerce')

# 2. Format to m/d. 
# Note: Use %m/%d for "04/15" or %#m/%#d for "4/15" on Windows.
merged_final['적용\n시점'] = merged_final['적용\n시점'].dt.strftime('%m/%d').fillna('')

C:\Users\user\AppData\Local\Temp\ipykernel_19392\1144699724.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  merged_final['적용\n시점'] = pd.to_datetime(merged_final['적용\n시점'], errors='coerce')

In [201]:
merged_final['진행상황'] =merged_final['진행상황'].replace(0,'')

In [205]:
merged_final['합의\n\/g'] = merged_final['합의\n\/g'].replace(0,'')

<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
<>:1: SyntaxWarning: invalid escape sequence '\/'
C:\Users\user\AppData\Local\Temp\ipykernel_19392\4237184804.py:1: SyntaxWarning: invalid escape sequence '\/'
  merged_final['합의\n\/g'] = merged_final['합의\n\/g'].replace(0,'')
C:\Users\user\AppData\Local\Temp\ipykernel_19392\4237184804.py:1: SyntaxWarning: invalid escape sequence '\/'
  merged_final['합의\n\/g'] = merged_final['합의\n\/g'].replace(0,'')

In [202]:
merged_final[merged_final['거래처'] == '이지패키지']

,거래처,1~3월매출,1~3월매출중량(TON),요청\n\/g,예상\n\/g,합의\n\/g,적용\n시점,진행상황,_merge
20,이지패키지,17163770.0,3.059,6.1,6.1,6.1,05/01,공문발송,both

In [206]:
merged_final

,거래처,1~3월매출,1~3월매출중량(TON),요청\n\/g,예상\n\/g,합의\n\/g,적용\n시점,진행상황,_merge
0,코웨이,184643610.0,26.060,8.295131,8.295131,,,,both
1,탭스인터내셔널,141198930.0,19.270,8.127552,8.127552,8.13,05/01,공문발송,both
2,중부스티로폼,101602764.0,19.108,6.170000,6.170000,,,운임 별도로 받고 있음,both
3,한국이노팩,87963786.0,16.980,6.100000,5.700000,5.7,04/15,공문발송,both
4,동진쎄미켐,89713290.0,15.522,6.700000,6.700000,,,,both
...,...,...,...,...,...,...,...,...,...
152,하비월드,231600.0,0.024,0.000000,0.000000,,,,right_only
153,찬푸드,19200.0,0.003,8.000000,8.000000,,,,left_only
154,CJ대한통운/아이스팩,31005504.0,0.000,0.000000,0.000000,,,,right_only
155,루이스벨라/아이스팩,382240.0,0.000,0.000000,0.000000,,,,right_only
156,케이듀/아이스팩,84000.0,0.000,0.000000,0.000000,,,,right_only

In [208]:
merged_final.to_excel("3월단가현황_raw2.xlsx")